name: Generate Index
on:
  push:
    paths:
      - 'post*.html'
      - 'generate-index.js'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: '20' }
      - run: npm init -y && npm install jsdom
      - run: node generate-index.js
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update index" || echo "No changes"
          git push
